apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>HELLO KUBECON</title>
    </head>
    <body>
        <h1>HELLO KUBECON</h1>
        <p>HELLO KUBECON</p>
    </body>
    </html>
